---

### 2. The SQL Schema (`schema.sql`)
Spring Boot will automatically run this file if you place it in `src/main/resources/schema.sql`.

```sql
-- Table Structure
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(38, 2) NOT NULL,
    category VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    date DATE NOT NULL
);

-- Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_category ON expenses(category);
CREATE INDEX IF NOT EXISTS idx_date ON expenses(date);